apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: stacksage
    user: stacksage
    secureJsonData:
      password: stacksage
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
